export const Images = {
  Splash: require("../Assets/Images/Splash.png"),
  Wallet: require("../Assets/Images/Wallet.png"),
  Setting: require("../Assets/Images/Setting.png"),
  Thumbnail: require("../Assets/Images/Thumbnail.png"),
  Vector: require("../Assets/Images/Vector.png"),
  down: require("../Assets/Images/down.png"),
  qrCode: require("../Assets/Images/qrCode.png"),
  transferToken: require("../Assets/Images/transferToken.png"),
  swapToken: require("../Assets/Images/swapToken.png"),
  Mantle: require("../Assets/Images/Mantle.jpg"),
  ethereum: require("../Assets/Images/ethereum.png"),
  scroll: require("../Assets/Images/scroll.png"),
  Base_Georli: require("../Assets/Images/Base_Georli.png"),
  Arbitrum_Goerl: require("../Assets/Images/Arbitrum_Goerl.png"),
  Cello: require("../Assets/Images/Cello.jpg"),
  DAI: require("../Assets/Images/DAI.png"),
  USDC: require("../Assets/Images/USDC.png"),
  USDT: require("../Assets/Images/USDT.png"),
};
