export const Screens = {
  Home: "Home",
  Splash: "Splash",
  Start: "Start",
  Login: "Login",
  UserName: "UserName",
  Password: "Password",
  AuthLoading: "AuthLoading",
  AuthSuccess: "AuthSuccess",
  RecoveryGuardians: "RecoveryGuardians",
  Guardian: "Guardian",
  ConfirmGuardian: "ConfirmGuardian",
  Settings: "Settings",
  BottomBar: "BottomBar",
  InitiateRecovery: "InitiateRecovery",
  RecoveryPassword: "RecoveryPassword",
  OnBoarding: "OnBoarding",

  Wallet: "Wallet",
  Transact: "Transact",
  Activity: "Activity",
  Recovery: "Recovery",
};
